name: Interaction
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        output1: ${{ steps.repo_var.outputs.var }}  
    steps:
      - uses: gradle/gradle-build-action@v2
        with: 
            gradle-version: 6.5
      - uses: actions/checkout@v2
      - name: Set repo variable
        run: |
          op=$(basename $(git remote show -n origin | grep Fetch | cut -d: -f2-))
          echo "repo_v=$op" >> $GITHUB_ENV
      - id: repo_var
        run: echo "::set-output name=var::${{ env.repo_v }}"   
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: gradle artifactoryPublish -b /home/runner/work/Gradle-tata-testing-without-cli/Gradle-tata-testing-without-cli/gradle-example-publish/build.gradle
        #run: gradle build -b /home/runner/work/Gradle-tata-testing-without-cli/Gradle-tata-testing-without-cli/gradle-example-publish/build.gradle
        #env: 
        #  JF_ARTIFACTORY_1: ${{ secrets.HARISH_CLI_GITHUB_ACTIONS }}
