name: Harishgoud latest testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: gradle build
      - name: jfrog cli setup
        uses: jfrog/setup-jfrog-cli@v2
      - name: Build with Gradle
        run: gradle publish
      # - name: Jfrog cli deploy  
      #   run: |
      #     # Ping the server
      #     jfrog rt ping
      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.HARISH_CLI_GITHUB_ACTIONS }}
      #- run: |
      #    jfrog rt ping
      #- run: |
      #    jfrog rt gradlec --global --server-id-resolve=artifactory --server-id-deploy=artifactory --repo-resolve=beaute-gradle-dev --repo-deploy=gradle-local
      #
      #   run: gradle deploy
      #   env: 
      #     JF_ARTIFACTORY_1: ${{ secrets.HARISH_CLI_GITHUB_ACTIONS }} 
      - name: Publish to Jfrog
        run: |
          jfrog rt gradle clean artifactoryPublish -b ../../
      #    jfrog rt bp
          
        env:
          JF_ARTIFACTORY_1: ${{ secrets.HARISH_CLI_GITHUB_ACTIONS }}
